### ISSUE TITLE
Error on debian

### ISSUE THREAD

**Issue by MrMelon54** [Koupah/Among-Us-Editor#33]
Starting up Among Us Editor version 1.6
Starting Rich Presence
Current gameHostOptions Hex: 
04 0A 01 00 00 00 00 00 00 E0 3F 00 00 80 3F 00 
00 C0 3F 00 00 A0 41 01 01 02 01 00 00 00 01 01 
0F 00 00 00 78 00 00 00 00 0F 01 01 00 00 

Current playerStats Hex: 
03 01 00 00 00 00 00 00 00 07 00 00 00 00 00 00 
00 01 00 00 00 00 00 00 00 02 00 00 00 00 00 00 
00 03 00 00 00 00 00 00 00 03 00 00 00 03 00 00 
00 03 00 00 00 02 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 00 00 

Exception Type: java.lang.Double
Method: compareTo

Origin Class: club.koupah.aue.gui.types.impl.custom.hostsettings.Float32Setting
Origin Method: update
Origin Line: 28
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Double
	at java.lang.Double.compareTo(Double.java:49)
	at javax.swing.SpinnerNumberModel.incrValue(SpinnerNumberModel.java:349)
	at javax.swing.SpinnerNumberModel.getPreviousValue(SpinnerNumberModel.java:388)
	at javax.swing.plaf.basic.BasicSpinnerUI.updateEnabledState(BasicSpinnerUI.java:501)
	at javax.swing.plaf.basic.BasicSpinnerUI.updateEnabledState(BasicSpinnerUI.java:481)
	at javax.swing.plaf.basic.BasicSpinnerUI.access$200(BasicSpinnerUI.java:50)
	at javax.swing.plaf.basic.BasicSpinnerUI$Handler.stateChanged(BasicSpinnerUI.java:1057)
	at javax.swing.JSpinner.fireStateChanged(JSpinner.java:458)
	at javax.swing.JSpinner$ModelListener.stateChanged(JSpinner.java:386)
	at javax.swing.AbstractSpinnerModel.fireStateChanged(AbstractSpinnerModel.java:119)
	at javax.swing.SpinnerNumberModel.setValue(SpinnerNumberModel.java:447)
	at javax.swing.JSpinner.setValue(JSpinner.java:354)
	at club.koupah.aue.gui.types.impl.custom.hostsettings.Float32Setting.update(Float32Setting.java:28)
	at club.koupah.aue.gui.types.impl.custom.hostsettings.Float32Setting.<init>(Float32Setting.java:22)
	at club.koupah.aue.Editor.addComponents(Editor.java:634)
	at club.koupah.aue.Editor.setupWindow(Editor.java:328)
	at club.koupah.AUEditorMain.main(AUEditorMain.java:109)

**Comment by Koupah** [comment]
Inside the discord I have provided a prerelease with this issue fixed, however I can add it as a prerelease on github if you'd like (or compile it yourself)

**Comment by MrMelon54** [comment]
Ok then I'll join the discord. Would be useful if you added that as a note on the github release for other people.
